/**
 * CLI output — writes project files and prints a summary table
 * with share links / client node information.
 */

import kleur from "kleur";
import type { ClientNode } from "../engines/xray/module-api.js";
import type { SaveProjectInput, ProjectData } from "../project/store.js";
import { saveProject } from "../project/store.js";

// ---------------------------------------------------------------------------
// Write project to disk
// ---------------------------------------------------------------------------

export interface WriteProjectInput {
  project: ProjectData;
  serverConfig: Record<string, unknown>;
  clientNodes: ClientNode[];
  files?: { name: string; content: string }[];
}

export function writeProject(input: WriteProjectInput): void {
  const readme = generateReadme(input.project, input.clientNodes);

  saveProject({
    project: input.project,
    serverConfig: input.serverConfig,
    readme,
    files: input.files,
  });

  console.log(kleur.green(`\n✓ Project "${input.project.name}" saved to output/${input.project.name}/`));
  console.log(kleur.gray(`  server.json  project.json  README.md`));
  if (input.files?.length) {
    console.log(kleur.gray(`  ${input.files.map(f => f.name).join("  ")}`));
  }
}

// ---------------------------------------------------------------------------
// Print summary table
// ---------------------------------------------------------------------------

export function printSummary(project: ProjectData, clientNodes: ClientNode[]): void {
  console.log();
  console.log(kleur.bold().cyan("══ Node Summary ══"));
  console.log();

  for (const node of clientNodes) {
    console.log(kleur.bold(`  ${node.remarks ?? node.protocol}`));
    console.log(kleur.gray(`    Protocol:  ${node.protocol}`));
    console.log(kleur.gray(`    Port:      ${node.port}`));
    console.log(kleur.gray(`    Network:   ${node.network}`));
    console.log(kleur.gray(`    Security:  ${node.security}`));

    if (node.extra) {
      for (const [key, val] of Object.entries(node.extra)) {
        if (key === "publicKey") {
          console.log(kleur.yellow(`    ${key.padEnd(10)} ${val}`));
        } else {
          console.log(kleur.gray(`    ${key.padEnd(10)} ${val}`));
        }
      }
    }

    // Generate VLESS share link
    const link = buildVlessShareLink(node);
    if (link) {
      console.log();
      console.log(kleur.green(`    Share link:`));
      console.log(kleur.white(`    ${link}`));
    }
    console.log();
  }

  console.log(kleur.bold().cyan("══ Credentials ══"));
  console.log();
  console.log(kleur.gray(`  UUID:       ${project.ctx.uuid}`));
  if (project.ctx.realityKeyPair) {
    console.log(kleur.yellow(`  PrivateKey: ${project.ctx.realityKeyPair.privateKey}`));
    console.log(kleur.yellow(`  PublicKey:  ${project.ctx.realityKeyPair.publicKey}`));
  }
  if (project.ctx.shortIds?.length) {
    console.log(kleur.gray(`  ShortIds:   ${project.ctx.shortIds.join(", ")}`));
  }
  console.log(kleur.gray(`  Password:   ${project.ctx.password}`));
  console.log();
}

// ---------------------------------------------------------------------------
// Generate README.md
// ---------------------------------------------------------------------------

function generateReadme(project: ProjectData, clientNodes: ClientNode[]): string {
  const lines: string[] = [];

  lines.push(`# ${project.name}`);
  lines.push("");
  lines.push("Generated by **configtools** — Xray-core 26.3 server config.");
  lines.push("");

  // Summary table
  lines.push("## Nodes");
  lines.push("");
  lines.push("| # | Protocol | Port | Network | Security |");
  lines.push("|---|----------|------|---------|----------|");
  for (let i = 0; i < clientNodes.length; i++) {
    const n = clientNodes[i];
    lines.push(`| ${i + 1} | ${n.protocol} | ${n.port} | ${n.network} | ${n.security} |`);
  }
  lines.push("");

  // Share links
  lines.push("## Share Links");
  lines.push("");
  for (const node of clientNodes) {
    const link = buildVlessShareLink(node);
    if (link) {
      lines.push(`**${node.remarks ?? node.protocol}**`);
      lines.push("```");
      lines.push(link);
      lines.push("```");
      lines.push("");
    }
  }

  // Credentials
  lines.push("## Credentials");
  lines.push("");
  lines.push(`- **UUID**: \`${project.ctx.uuid}\``);
  if (project.ctx.realityKeyPair) {
    lines.push(`- **Reality PrivateKey**: \`${project.ctx.realityKeyPair.privateKey}\``);
    lines.push(`- **Reality PublicKey**: \`${project.ctx.realityKeyPair.publicKey}\``);
  }
  if (project.ctx.shortIds?.length) {
    lines.push(`- **Reality ShortIds**: \`${project.ctx.shortIds.join("`, `")}\``);
  }
  lines.push(`- **Password**: \`${project.ctx.password}\``);
  lines.push("");

  // Advice
  lines.push("## Notes");
  lines.push("");
  lines.push("- `server.json` is the Xray config. Edit it freely, then:");
  lines.push("  - `configtools format <name>` — reformat");
  lines.push("  - `configtools check <name>` — validate");
  lines.push("  - `configtools edit <name>` — re-prompt and rebuild");
  lines.push("- For Reality clients, set `fingerprint: chrome` and use the **PublicKey** above.");
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Build VLESS share link
// ---------------------------------------------------------------------------

function buildVlessShareLink(node: ClientNode): string | null {
  if (node.protocol !== "vless") return null;

  const params = new URLSearchParams();

  switch (node.security) {
    case "reality":
      params.set("type", node.network);
      params.set("security", "reality");
      params.set("pbk", node.extra?.publicKey ?? "");
      params.set("fp", node.extra?.fingerprint ?? "chrome");
      params.set("sni", node.extra?.serverName ?? "");
      params.set("sid", node.extra?.shortId ?? "");
      params.set("flow", node.extra?.flow ?? "");
      break;
    case "tls":
      params.set("type", node.network);
      params.set("security", "tls");
      params.set("fp", node.extra?.fingerprint ?? "chrome");
      params.set("sni", node.extra?.sni ?? "");
      if (node.network === "ws" && node.extra?.path) {
        params.set("path", node.extra.path);
      }
      if (node.network === "ws" && node.extra?.host) {
        params.set("host", node.extra.host);
      }
      if (node.network === "grpc" && node.extra?.serviceName) {
        params.set("serviceName", node.extra.serviceName);
      }
      if (node.network === "grpc" && node.extra?.mode) {
        params.set("mode", node.extra.mode);
      }
      break;
    default:
      return null;
  }

  // We don't include address host — the user fills that in.
  // Use a placeholder.
  const host = "YOUR_SERVER_IP";
  const uuid = node.extra?.uuid ?? "";
  return `vless://${uuid}@${host}:${node.port}?${params.toString()}#${encodeURIComponent(node.remarks ?? "vless")}`;
}
